# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code, and run tests across different versions of node.
# For more information, see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm i --force

      # Set environment variables
      - name: Set environment variables
        env:
          PORT: 3000
          DATABASE_URI: mongodb+srv://imuhammadabbas:tfsuTiizv48kjUDo@sensocoffeecluster.eky2nzd.mongodb.net/?retryWrites=true&w=majority&appName=SensoCoffeeCluster
          PAYLOAD_SECRET: fa11185ccccd6364bd6aea5a
          PAYLOAD_PUBLIC_SERVER_URL: http://localhost:80
          NEXT_PUBLIC_SERVER_URL: http://localhost:80
          STRIPE_SECRET_KEY: ""
          PAYLOAD_PUBLIC_STRIPE_IS_TEST_KEY: true
          NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY: ""
          STRIPE_WEBHOOKS_SIGNING_SECRET: ""
          NEXT_PUBLIC_IS_LIVE: true
          PAYLOAD_PUBLIC_DRAFT_SECRET: demo-draft-secret
          NEXT_PRIVATE_DRAFT_SECRET: demo-draft-secret
          REVALIDATION_KEY: demo-revalation-key
          NEXT_PRIVATE_REVALIDATION_KEY: demo-revalation-key
          NEXT_PUBLIC_INSTAGRAM_TOKEN: IGQWRNbE5iM05kUjU2MEZAnd0EwbUdUaTJ2aTFfZAW5na29qaDZACbnMzSmNaZAHhqX1pIWU9LaWFDalF3SmVxWTNkUDdvWlk4eHRNM1EzaTJrbk9pLW8wMzFVY2xNUEZACRVFOSHJZANC1MWkRZAMmdpODZA1XzRUaVhqd0kZD
      - run: npm run build --if-present
      - run: npm test
